

export const menu = [
  {
    title: 'WIADOMOŚCI',
    icon: 'mail',
    page: 'Messages',
    forAppAdmin: true,
    forBuildingAdmin: true,
    forBoard: true,
    forResident: true,
    forAll:true,
  },
  {
    title: 'TABLICA OGŁOSZEŃ',
    icon: 'pushpino',
    page: 'Main',
    forAppAdmin: true,
    forBuildingAdmin: true,
    forBoard: true,
    forResident: true,
    forAll:false,
  },
  {
    title: 'GŁOSOWANIA',
    icon: 'carryout',
    page: 'Main',
    forAppAdmin: true,
    forBuildingAdmin: true,
    forBoard: true,
    forResident: true,
    forAll:false,
  },
  {
    title: 'ANKIETY',
    icon: 'linechart',
    page: 'Main',
    forAppAdmin: true,
    forBuildingAdmin: true,
    forBoard: true,
    forResident: true,
    forAll:false,
  },
  {
    title: 'DOKUMENTY',
    icon: 'folderopen',
    page: 'Main',
    forAppAdmin: true,
    forBuildingAdmin: true,
    forBoard: true,
    forResident: true,
    forAll:false,
  },
  {
    title: 'AWARIE',
    icon: 'bells',
    page: 'Failure',
    forAppAdmin: false,
    forBuildingAdmin: false,
    forBoard: false,
    forResident: true,
    forAll:false,
  },
  {
    title: 'ZAPROSZENIA',
    icon: 'mail',
    page: 'MyInvitations',
    forAppAdmin: true,
    forBuildingAdmin: true,
    forBoard: true,
    forResident: true,
    forAll:true,
  },
  {
    title: 'USTAWIENIA',
    icon: 'setting',
    page: 'Main',
    forAppAdmin: true,
    forBuildingAdmin: true,
    forBoard: true,
    forResident: true,
    forAll:true,
  },
];


