

export const menu = [
  {
    title: 'WIADOMOŚCI',
    icon: require('../../assets/icons/envelope.png'),
    page: 'Messages',
    forAppAdmin: true,
    forBuildingAdmin: true,
    forBoard: true,
    forResident: true,
    forAll:true,
  },
  {
    title: 'TABLICA OGŁOSZEŃ',
    icon: require('../../assets/icons/pin.png'),
    page: 'Annoucment',
    forAppAdmin: true,
    forBuildingAdmin: true,
    forBoard: true,
    forResident: true,
    forAll:false,
  },
  {
    title: 'GŁOSOWANIA I ANKIETY',
    icon: require('../../assets/icons/vote.png'),
    page: 'Main',
    forAppAdmin: true,
    forBuildingAdmin: true,
    forBoard: true,
    forResident: true,
    forAll:false,
  },
  // {
  //   title: 'ANKIETY',
  //   icon: require('../../assets/icons/survey.png'),
  //   page: 'Main',
  //   forAppAdmin: true,
  //   forBuildingAdmin: true,
  //   forBoard: true,
  //   forResident: true,
  //   forAll:false,
  // },
  {
    title: 'DOKUMENTY',
    icon: require('../../assets/icons/paper-clip.png'),
    page: 'Main',
    forAppAdmin: true,
    forBuildingAdmin: true,
    forBoard: true,
    forResident: true,
    forAll:false,
  },
  {
    title: 'ZGŁOSZENIA',
    icon: require('../../assets/icons/notification.png'),
    page: 'Failure',
    forAppAdmin: false,
    forBuildingAdmin: false,
    forBoard: false,
    forResident: true,
    forAll:false,
  },
  {
    title: 'ZAPROSZENIA',
    icon: require('../../assets/icons/invitation.png'),
    page: 'MyInvitations',
    forAppAdmin: true,
    forBuildingAdmin: true,
    forBoard: true,
    forResident: true,
    forAll:true,
  },
  // {
  //   title: 'USTAWIENIA',
  //   icon: 'setting',
  //   page: 'Main',
  //   forAppAdmin: true,
  //   forBuildingAdmin: true,
  //   forBoard: true,
  //   forResident: true,
  //   forAll:true,
  // },
];


